Bugfix - docker pull fail to pass credentials to a remote agent
jfrog/jenkins-artifactory-plugin pull request #347
Opened 2020-10-04 08:55 UTC by Or-Gabay

- [ ] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
-----

2020-10-21 08:42 UTC, yahavi requested changes

2020-10-21 08:42 UTC, yahavi commented on src/test/java/org/jfrog/hudson/pipeline/integration/CommonITestsPipeline.java
> +        String host = System.getenv("JENKINS_ARTIFACTORY_DOCKER_HOST");
```suggestion
```

2020-10-21 08:42 UTC, yahavi commented on src/test/java/org/jfrog/hudson/pipeline/integration/CommonITestsPipeline.java
> +        // Get image name
```suggestion
        // Assert 'JENKINS_ARTIFACTORY_DOCKER_PULL_DOMAIN' environment variable exist
```

2020-10-21 08:42 UTC, yahavi commented on src/test/java/org/jfrog/hudson/pipeline/integration/CommonITestsPipeline.java
> +        assertEquals(null, module.getArtifacts());
```suggestion
        assertNull(module.getArtifacts());
```

2020-10-21 08:42 UTC, yahavi commented on src/test/java/org/jfrog/hudson/pipeline/integration/CommonITestsPipeline.java
> +        assertTrue(module.getDependencies().size() > 0);
I suggest to check that the actual image exist with the image name, if possible

2020-10-21 08:42 UTC, yahavi commented on src/main/java/org/jfrog/hudson/pipeline/scripted/steps/DockerPullStep.java
>                  getContext().onFailure(new MissingArgumentException("Missing 'image' parameter"));
Please avoid MissingArgumentException. See: https://github.com/jfrog/jenkins-artifactory-plugin/pull/327
```suggestion
                getContext().onFailure(new AbortException("Missing 'image' parameter"));
```

2020-10-21 08:42 UTC, yahavi commented on src/main/java/org/jfrog/hudson/pipeline/scripted/steps/DockerPullStep.java
> +                getContext().onFailure(new MissingArgumentException("Missing 'targetRepo' parameter"));
```suggestion
                getContext().onFailure(new AbortException("Missing 'targetRepo' parameter"));
```

2020-10-22 07:46 UTC, Or-Gabay commented on src/main/java/org/jfrog/hudson/pipeline/common/types/Docker.java
> -    public void pull(String imageTag) {
We are not able to collect build info if there is no repository. There is no documentation for that command so have no good reason to keep supporting that.

2020-10-22 07:46 UTC, Or-Gabay commented on src/main/java/org/jfrog/hudson/pipeline/common/types/Docker.java
> -    public void pull(String imageTag, BuildInfo providedBuildInfo) {
https://github.com/jfrog/jenkins-artifactory-plugin/pull/347#discussion_r509948493

2020-10-22 09:37 UTC, Or-Gabay commented on src/main/java/org/jfrog/hudson/pipeline/declarative/steps/docker/DockerPullStep.java
> +    public DockerPullStep(String serverId, String image, String targetRepo, String javaArgs) {
Removed

2020-10-25 10:01 UTC, Or-Gabay commented on src/main/java/org/jfrog/hudson/pipeline/declarative/steps/docker/DockerPullStep.java
> +        private transient DockerPullStep step;
For some reason, the credentials inside ```step``` won't pass to the agent node.

2020-10-26 15:52 UTC, merged