Support for Artifactory Projects
jfrog/jenkins-artifactory-plugin pull request #449
Opened 2021-03-31 16:33 UTC by Or-Geva

- [ ] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
-----

2021-05-12 18:35 UTC, eyalbe4 requested changes
I suggest we add one integration test (a pipeline script), which publishes the build-info into project, and then validates that the build-info was indeed published to that project.

2021-05-13 05:25 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/pipeline/common/types/buildInfo/BuildInfo.java
> +        if (StringUtils.isNotEmpty(project)) {
Removed

2021-05-13 05:26 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/pipeline/common/types/PromotionConfig.java
> +        if (StringUtils.isNotEmpty(project)){
Removed

2021-05-13 05:27 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/pipeline/declarative/steps/generic/EditPropsStep.java
> +        if (StringUtils.isNotEmpty(project)) {
Removed

2021-05-13 05:27 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/pipeline/declarative/steps/generic/GenericStep.java
> +        if (StringUtils.isNotEmpty(project)) {
Removed

2021-05-13 05:33 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/pipeline/declarative/utils/DeclarativePipelineUtils.java
> +            if (StringUtils.isNotBlank(project)) {
Yes, otherwise we may override the last buildinfo's project if it exists

2021-05-13 05:33 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/pipeline/declarative/steps/CollectIssuesStep.java
> +        if (StringUtils.isNotEmpty(project)) {
Removed

2021-05-13 05:34 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/util/ExtractorUtils.java
> +        if (StringUtils.isNotBlank(project)) {
Removed

2021-05-13 05:35 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/pipeline/common/types/buildInfo/Issues.java
> +        if (StringUtils.isNotEmpty(project)) {
Removed

2021-05-13 06:59 UTC, Or-Geva commented on src/main/java/org/jfrog/hudson/pipeline/declarative/utils/DeclarativePipelineUtils.java
> +            if (StringUtils.isNotBlank(project)) {
Removed

2021-05-14 12:54 UTC, merged