Stay on step context Node when finding root workspace
jfrog/jenkins-artifactory-plugin pull request #616
Opened 2022-01-17 13:46 UTC by capadgett

- [ ] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
-----
This change #432 broke finding the root workspace in a very specific circumstance:
* two parallel stages running on different agents (Linux and Windows)
* resource locks used to control stage timings - i.e. to prevent publishing on platform before the other successfully builds

The pseudo pipeline below illustrates how the issue can be triggered:
```
pipeline {
    agent none
    stages {
        stage('Build and Publish') {
            failFast true
            parallel {
                stage('Build and Publish - Linux') {
                    agent { label 'linux' }
                    stages {
                        stage("Build - Linux") { steps { lock(resource: "linux-publish") { compile() } } }
                        stage('Publish - Linux') { steps { lock(resource: "linux-publish", extra: [[resource: "windows-publish"]]) { publish() } } }
                    }
                }
                stage('Build and Publish - Windows') {
                    agent { label 'windows' }
                    stages {
                        stage("Build - Windows") { steps { lock(resource: "windows-publish") { compile() } } }
                        stage('Publish - Windows') { steps { lock(resource: "windows-publish", extra: [[resource: "linux-publish"]]) { publish() } } }
                    }
                }
            }
        }
    }
}
```
where the `publish()` steps are what call the RT steps.

The behavior I see is that the root workspace found is for the wrong Node (the Linux node for the stage running on Windows). Obviously this breaks things.

This PR checks that the root workspace found is on the same Node as the step's context, if not null.

2022-01-17 13:50 UTC, capadgett commented
I have read the CLA Document and I hereby sign the CLA

2022-02-21 07:34 UTC, yahavi requested changes
@capadgett,
Thanks for this contribution!
Please consider my inline comments.

2022-02-21 07:34 UTC, yahavi commented on src/main/java/org/jfrog/hudson/pipeline/common/Utils.java
> +     * @param contextNode Node for the current step context or null.
```suggestion
     * @param execution   - The execution of the workflow run.
     * @param contextNode - Node for the current step context or null.
```

2022-02-21 07:34 UTC, yahavi commented on src/main/java/org/jfrog/hudson/pipeline/common/Utils.java
> +            // stay on the contextNode if not null
```suggestion
            // Stay on the contextNode if not null
```

2022-02-21 07:34 UTC, yahavi commented on src/main/java/org/jfrog/hudson/pipeline/common/Utils.java
> +        // get the current node from context
```suggestion
        // Get the current node from context
```

2022-02-21 07:34 UTC, yahavi commented on src/main/java/org/jfrog/hudson/pipeline/common/Utils.java
> +        // get the workspace from the flow (if it matches the context's node)
```suggestion
        // Get the workspace from the flow (if it matches the context's node)
```

2022-02-21 11:51 UTC, capadgett commented
@yahavi Thanks for the suggestions! All applied.

2022-02-21 15:43 UTC, talarian1 commented on src/main/java/org/jfrog/hudson/pipeline/common/Utils.java
> +            if (workspaceAction != null && ((contextNode != null && contextNode.getNodeName() == workspaceAction.getNode()) || contextNode == null)) {
```suggestion
            if (workspaceAction != null && (contextNode == null || StringUtils.equals(contextNode.getNodeName(), workspaceAction.getNode()))) {
```

2022-02-21 17:02 UTC, merged

2022-02-21 17:02 UTC, yahavi commented
Thanks, @capadgett!

2022-02-21 17:03 UTC, capadgett commented
Glad to help. Thanks all for the reviews!

2022-03-16 16:50 UTC, yahavi commented
@capadgett,
Jenkins Artifactory plugin 3.16.0 is released and includes this fix.
Feel free to upgrade and add your feedback on that!